### ISSUE TITLE
Define Bootcamp Agenda

### ISSUE THREAD

**Issue by felipecruz91** [kamstrupmalagameetups/Global-Azure-Bootcamp-2019#1]
We have to come up with a defined agenda for the Bootcamp.
Let's do it based on the following poll's results:

https://www.meetup.com/Kamstrup-Malaga/polls/1275493/?pollId=1275493

Any more ideas are welcome!

**Comment by jecaestevez** [comment]
I just created a c4p in bit.ly/c4pGABMalaga to get different proposals from the community

**Comment by felipecruz91** [comment]
@jecaestevez Upload the picture you took yesterday from the whiteboard

**Comment by felipecruz91** [comment]
### Talks

| Topic | Title | Speaker/s |
| --- | --- | --- |
| `Azure Container Instances` | TBD | @jecaestevez 
| `Azure Cosmos DB` | Managing gazillion of data in your UI - Materialized View Pattern | @felipecruz91 
| `Azure Cosmos DB` | Managing gazillion of data in your UI - Pagination | @mireyarodriguezs 
| `Azure Databricks` | TBD | TBD
| `Azure DataFactory` | TBD | TBD
| `Azure EventHubs` | TBD | TBD
| `Azure Functions` | How to go _serverless_ | @mireyarodriguezs 
|`Azure Machine Learning` | TBD | Bravent Speaker 1
|`Azure Machine Learning` | TBD | Bravent Speaker 2
|`Azure Service Bus` | TBD | TBD
|`Azure Service Fabric` | TBD | TBD
|`Azure SignalR` | TBD | @AntonioJDios 

### Hands-on labs

| Topic | Title | Speaker/s |
| --- | --- | --- |
| `Azure Cognitive Services` | TBD | Felipe

**Comment by Beelzenef** [comment]
Is this table on the website? Many thanks!

**Comment by jecaestevez** [comment]
> Is this table on the website? Many thanks!
Hi Elena, this table it was just a draft of what we wanted to have you can find the final agenda in https://azuremalaga.wordpress.com/2019/04/15/agenda/
